name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    # When rustup is updated, it tries to replace its binary, which on Windows is somehow locked.
    # This can result in the CI failure, see: https://github.com/rust-lang/rustup/issues/3029
    - run: |
        rustup set auto-self-update disable
        rustup toolchain install nightly --profile minimal
        rustup default nightly
    
    - name: Rust Cache
      uses: Swatinem/rust-cache@v2.2.1

    - name: Run check
      run: cargo check
